service: news-aggregator
package:
  exclude:
    - environment.yml
provider:
  name: aws
  runtime: python3.6
  environment: ${file(environment.yml)}
functions:
  topArticles:
    handler: handler.top_articles
    events:
      - http:
          path: /top
          method: get
  queryArticle:
    handler: handler.query_article
    events:
      - http:
          path: /query
          method: get
plugins:
  - serverless-python-requirements
